### ISSUE TITLE
Some bpläne have exactly the same polygon

### ISSUE THREAD

**Issue by MagdaN** [liqd/django_zbp#16]
which means that the calculated point is exactly the same and therefore it is impossible to click both of them.

@der-john do you think you can adapt  your Point calculation in a way that you check, that the point does not exist, yet?

**Comment by MagdaN** [comment]
I did some research to find out how many bpläne have that problem and I think about 80

**Comment by der-john** [comment]
A minimal distance between two bplan points needs to be kept.
