### ISSUE TITLE
street without number should return coordinates of street lowest number

### ISSUE THREAD

**Issue by MagdaN** [liqd/django_zbp#20]
@petbali will suggest this on Wed, Dec 14, 2016.

**Comment by localgrr** [comment]
Or middle of the street ?

**Comment by der-john** [comment]
We agreed on a first step in this direction: If the search string doesn't include a number, the error should ask the user if he forgot it.

**Comment by der-john** [comment]
> Or middle of the street ?

I think that's a lot more challenging and not much more helpful.

**Comment by MagdaN** [comment]
yeah, take beginning of the street

**Comment by der-john** [comment]
> @petbali will suggest this on Wed, Dec 14, 2016.

The senatsverwaltung approves of the feature.
