### ISSUE TITLE
bplan map embed not correctly shown, map view missing

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/django_zbp#324]
**URL:** https://www.stadtentwicklung.berlin.de/planen/b-planverfahren/berlin/index.shtml
**user:** any
**expected behaviour:** I can see a map, switch from list to map view
**behaviour:** map and switch (Ansicht) are not displayed
**important screensize:**
**device & browser:** seems to only appear on big sur/apple, chrome only
**Comment/Question:** 

Screenshot?
<img width="928" alt="Bildschirmfoto 2021-03-05 um 10 49 29" src="https://user-images.githubusercontent.com/35491681/110099030-23dfac80-7da1-11eb-806a-68e74c2484f8.png">

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 yes, I can see everything if not embedded.

**Comment by fuzzylogic2000** [comment]
@rmader If @CarolingerSeilchenspringer  can see anything when not embedded, that means, it's their bug, not ours, right?
