### ISSUE TITLE
map credits: leaflet is not shown

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/django_zbp#348]
https://bplan-stage.liqd.net/berlin/

we now show maptiler and open street map but no longer leaflet, which was there from the beginning. In meinBerlin we show all three (https://mein.berlin.de/projekte/) and should do the same here.

**Comment by fuzzylogic2000** [comment]
@rmader  last issue to answer to? :)

**Comment by rmader** [comment]
AFAIK there's no need to show leaflet anywhere - it's just shown by default. So instead of adding it, we should IMO rather remove it from mB and a+. Because maptiler and openstreetmap provide us with actual data under copyright while leaflet is just one more js package we use.

**Comment by CarolingerSeilchenspringer** [comment]
@rmader Can we look that up somewhere to be sure on it? Then we wouldn't have to do it of course.

**Comment by rmader** [comment]
https://github.com/Leaflet/Leaflet/blob/master/LICENSE and https://leafletjs.com/reference-1.2.0.html#control-attribution

According to the Leaflet license it is free software and we're free to modify it - the license doesn't mention any obligation to show the `Leaflet` attribution and the docs state that `Leaflet` is just the default value which can easily be changed, without mentioning any obligation to keep Leaflet in.

**Comment by CarolingerSeilchenspringer** [comment]
@rmader thanks! Then I will close this issue and you are free to deploy on prod.
