### ISSUE TITLE
Ticks in checkboxes (dis)appear very slowly on big screens

### ISSUE THREAD

**Issue by PetBali** [liqd/django_zbp#40]
On big screens the ticks of the checkboxes (in Beteiligung, im Verfahren, Festgesetzt) function very slowly.

![bildschirmfoto 2016-12-06 um 16 33 54](https://cloud.githubusercontent.com/assets/19797242/20931906/fe235f9e-bbd2-11e6-9051-6ee82133ae3d.png)

**Comment by der-john** [comment]
I can't reproduce the issue. #39 might change the behavior.

**Comment by fuzzylogic2000** [comment]
Fine now!
