### ISSUE TITLE
missing scan_www

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/django_zbp#412]
https://github.com/liqd/a4-meinberlin/issues/3792

**Comment by fuzzylogic2000** [comment]
Looks like all the `_www` fields that should be filled with this https://github.com/liqd/django_zbp/blob/d298b7c373276e7bda8da3a3ee943802f67669f0/bplan/management/commands/load_bplan.py#L207 are empty:
`>>> from bplan.models import BPlan
>>> BPlan.objects.filter(scan_www__isnull=False)
<QuerySet []>
>>> BPlan.objects.filter(ausleg_www__isnull=False)
<QuerySet []>
>>> BPlan.objects.filter(grund_www__isnull=False)
<QuerySet []>`

**Comment by fuzzylogic2000** [comment]
It is all capitals (`SCAN_WWW`) now...

**Comment by fuzzylogic2000** [comment]
And the capitalization wasn't the problem (that also works for `festsg_am = feature.get("festsg_am").date`, even though it's `FESTSG_AM` in the geojson.

The problem is the changed format. It used to be 
https://github.com/liqd/django_zbp/blob/d298b7c373276e7bda8da3a3ee943802f67669f0/bplan/management/commands/load_bplan.py#L208
and now it's just the url.

@CarolingerSeilchenspringer That means the url format changed in the FIS broker and noone told us. When there was the schema change, it was still the old weird format. (We used it in the fixtures: https://github.com/liqd/django_zbp/commit/5d55eb6e1cca504950178bf34f641d4718f840e3)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 oh, can you see when that happened? But I read that you found a solution to it, right?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer No, I can't. I just saw that it changed. But yes, I think I found the fix. Will try on stage.
