### ISSUE TITLE
update management script to load addresses from FIS Broker once a month 

### ISSUE THREAD

**Issue by MagdaN** [liqd/django_zbp#48]

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer @goapunk Ah, and another problem: we should also from time to time load the new addresses...

**Comment by goapunk** [comment]
the one from ``http://fbarc.stadt-berlin.de/FIS_Broker_Atom/AD/AD_AdressenBerlin.zip`` ? That link doesn't work for me anymore

**Comment by goapunk** [comment]
https://fbinter.stadt-berlin.de/fb/atom/AD/AD_AdressenBerlin.zip seems to be the possible new address?

**Comment by CarolingerSeilchenspringer** [comment]
@goapunk is this still relevant? I will add to the milestone for next release, please take out if not imporant.

**Comment by goapunk** [comment]
@CarolingerSeilchenspringer that's kinda up to you, it's a nice to have that the addresses (e.g. street names) used for the search are automatically updated once a month. Otherwise they might become out of date

**Comment by CarolingerSeilchenspringer** [comment]
@goapunk got it, will close the issue then.
