### ISSUE TITLE
B-Plan-Map: tiles are not displayed in IE

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/django_zbp#83]
using IE the tiles of the b-plan-map are not displayed. Can we fix this quickly?

copied from https://github.com/liqd/a4-meinberlin/issues/2229

**Comment by MagdaN** [comment]
I checked it on browserstack and there is the 403 error again (meaning our token is invalid) but this only happens with ie11. Very strange. @rmader do you have an idea?

**Comment by rmader** [comment]
Fixed by https://github.com/liqd/django_zbp/commit/832217a8fc9ecce358ea163ddb2e8dc59f44f57b, but don't know why
